package hue.captains.singapura.js.homing.planview.widgets;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/** The plan-phase party's type, as the page has it: {@code PLAN_PHASE}, generated from {@link PlanPhaseContent#TYPE}. */
public record PlanPhaseContentModule() implements EsModule<PlanPhaseContentModule>, SelfContent {

    public static final PlanPhaseContentModule INSTANCE = new PlanPhaseContentModule();

    public record PLAN_PHASE() implements Exportable._Constant<PlanPhaseContentModule> {}

    @Override public ImportsFor<PlanPhaseContentModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<PlanPhaseContentModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new PLAN_PHASE())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by PlanPhaseContentModule from PlanPhaseContent.TYPE - do not hand-edit.", PlanPhaseContent.TYPE.js());
    }
}
