package hue.captains.singapura.js.homing.planview.widgets;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/** The plan-head party's type, as the page has it: {@code PLAN_HEAD}, generated from {@link PlanHeadContent#TYPE}. */
public record PlanHeadContentModule() implements EsModule<PlanHeadContentModule>, SelfContent {

    public static final PlanHeadContentModule INSTANCE = new PlanHeadContentModule();

    public record PLAN_HEAD() implements Exportable._Constant<PlanHeadContentModule> {}

    @Override public ImportsFor<PlanHeadContentModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<PlanHeadContentModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new PLAN_HEAD())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by PlanHeadContentModule from PlanHeadContent.TYPE - do not hand-edit.", PlanHeadContent.TYPE.js());
    }
}
