package hue.captains.singapura.js.homing.planview.widgets;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/** The plan-list party's type, as the page has it: {@code PLAN_LIST}, generated from {@link PlanListContent#TYPE}. */
public record PlanListContentModule() implements EsModule<PlanListContentModule>, SelfContent {

    public static final PlanListContentModule INSTANCE = new PlanListContentModule();

    public record PLAN_LIST() implements Exportable._Constant<PlanListContentModule> {}

    @Override public ImportsFor<PlanListContentModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<PlanListContentModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new PLAN_LIST())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by PlanListContentModule from PlanListContent.TYPE - do not hand-edit.", PlanListContent.TYPE.js());
    }
}
