package hue.captains.singapura.js.homing.docview.widgets;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/** The code party's type, as the page has it: {@code CODE}, generated from {@link CodeContent#TYPE}. */
public record CodeContentModule() implements EsModule<CodeContentModule>, SelfContent {

    public static final CodeContentModule INSTANCE = new CodeContentModule();

    public record CODE() implements Exportable._Constant<CodeContentModule> {}

    @Override public ImportsFor<CodeContentModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<CodeContentModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new CODE())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by CodeContentModule from CodeContent.TYPE - do not hand-edit.", CodeContent.TYPE.js());
    }
}
