package hue.captains.singapura.js.homing.docview.widgets;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/** The diagram party's type, as the page has it: {@code DIAGRAM}, generated from {@link DiagramContent#TYPE}. */
public record DiagramContentModule() implements EsModule<DiagramContentModule>, SelfContent {

    public static final DiagramContentModule INSTANCE = new DiagramContentModule();

    public record DIAGRAM() implements Exportable._Constant<DiagramContentModule> {}

    @Override public ImportsFor<DiagramContentModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<DiagramContentModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new DIAGRAM())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by DiagramContentModule from DiagramContent.TYPE - do not hand-edit.", DiagramContent.TYPE.js());
    }
}
