package hue.captains.singapura.js.homing.docview.widgets;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/** The image party's type, as the page has it: {@code IMAGE}, generated from {@link ImageContent#TYPE}. */
public record ImageContentModule() implements EsModule<ImageContentModule>, SelfContent {

    public static final ImageContentModule INSTANCE = new ImageContentModule();

    public record IMAGE() implements Exportable._Constant<ImageContentModule> {}

    @Override public ImportsFor<ImageContentModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<ImageContentModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new IMAGE())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by ImageContentModule from ImageContent.TYPE - do not hand-edit.", ImageContent.TYPE.js());
    }
}
