package hue.captains.singapura.js.homing.docview.widgets;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;
import hue.captains.singapura.js.homing.libs.MermaidProxyModule;

import java.util.List;

/**
 * Where the mermaid library is, and the ground its diagrams are drawn for - both resolved, not
 * written. {@code MERMAID_LIBRARY}: the address core's {@link MermaidProxyModule} is served at, so
 * the engine imports it lazily by an address the server knows; the proxy is the one seam that
 * reaches the network, and a deployment points it elsewhere with {@code ExternalModuleUrlRegistry}.
 * {@code MERMAID_GROUND}: the design's variable for the plate's surface
 * ({@link DocWidgetStyles#PLATE_GROUND}), which the engine reads to draw dark on a dark one.
 */
public record MermaidLibraryModule() implements EsModule<MermaidLibraryModule>, SelfContent {

    public static final MermaidLibraryModule INSTANCE = new MermaidLibraryModule();

    public record MERMAID_LIBRARY() implements Exportable._Constant<MermaidLibraryModule> {}

    public record MERMAID_GROUND() implements Exportable._Constant<MermaidLibraryModule> {}

    @Override public ImportsFor<MermaidLibraryModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<MermaidLibraryModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new MERMAID_LIBRARY(), new MERMAID_GROUND())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        String ground = DocWidgetStyles.PLATE_GROUND.var("background-color");
        return List.of("// Generated by MermaidLibraryModule - where core's mermaid proxy is served, and the design's variable for a diagram's ground.",
                "const MERMAID_LIBRARY = " + str(resolver.resolve(MermaidProxyModule.INSTANCE).toString()) + ";",
                "const MERMAID_GROUND = " + str(ground.substring("var(".length(), ground.length() - 1)) + ";");
    }

    private static String str(String s) { return "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""; }
}
