package hue.captains.singapura.js.homing.docview.widgets;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/** The prose party's type, as the page has it: {@code PROSE}, generated from {@link ProseContent#TYPE}. */
public record ProseContentModule() implements EsModule<ProseContentModule>, SelfContent {

    public static final ProseContentModule INSTANCE = new ProseContentModule();

    public record PROSE() implements Exportable._Constant<ProseContentModule> {}

    @Override public ImportsFor<ProseContentModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<ProseContentModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new PROSE())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by ProseContentModule from ProseContent.TYPE - do not hand-edit.", ProseContent.TYPE.js());
    }
}
