package hue.captains.singapura.js.homing.docview.widgets;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/** The reading party's type, as the page has it: {@code READING}, generated from {@link ReadingParty#TYPE}. */
public record ReadingPartyModule() implements EsModule<ReadingPartyModule>, SelfContent {

    public static final ReadingPartyModule INSTANCE = new ReadingPartyModule();

    public record READING() implements Exportable._Constant<ReadingPartyModule> {}

    @Override public ImportsFor<ReadingPartyModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<ReadingPartyModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new READING())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by ReadingPartyModule from ReadingParty.TYPE - do not hand-edit.", ReadingParty.TYPE.js());
    }
}
