package hue.captains.singapura.js.homing.docview.widgets;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/** The references party's type, as the page has it: {@code REFERENCES}, generated from {@link ReferencesContent#TYPE}. */
public record ReferencesContentModule() implements EsModule<ReferencesContentModule>, SelfContent {

    public static final ReferencesContentModule INSTANCE = new ReferencesContentModule();

    public record REFERENCES() implements Exportable._Constant<ReferencesContentModule> {}

    @Override public ImportsFor<ReferencesContentModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<ReferencesContentModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new REFERENCES())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by ReferencesContentModule from ReferencesContent.TYPE - do not hand-edit.", ReferencesContent.TYPE.js());
    }
}
