package hue.captains.singapura.js.homing.docview.widgets;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/** The table party's type, as the page has it: {@code TABLE}, generated from {@link TableContent#TYPE}. */
public record TableContentModule() implements EsModule<TableContentModule>, SelfContent {

    public static final TableContentModule INSTANCE = new TableContentModule();

    public record TABLE() implements Exportable._Constant<TableContentModule> {}

    @Override public ImportsFor<TableContentModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<TableContentModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new TABLE())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by TableContentModule from TableContent.TYPE - do not hand-edit.", TableContent.TYPE.js());
    }
}
