package hue.captains.singapura.js.homing.conformance.workbench;

import hue.captains.singapura.js.homing.codec.ObjectDefinition;
import hue.captains.singapura.js.homing.codec.ecma.EcmaDefinitionCodeGen;
import hue.captains.singapura.js.homing.codec.ecma.EcmaFunctionsCodeGen;
import hue.captains.singapura.js.homing.conformance.report.gen.ReportCodecManifest;
import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.ArrayList;
import java.util.List;

/**
 * The report's codecs, as the page has them: a typed class for each report record and a codec
 * to read it from the wire, generated from {@link ReportCodecManifest} as it is served - so the
 * JS reads exactly what the Java codecs write ({@code ReportFeed}).
 */
public record ReportCodecsModule() implements EsModule<ReportCodecsModule>, SelfContent {

    public static final ReportCodecsModule INSTANCE = new ReportCodecsModule();

    public record ConformanceReport() implements Exportable._Class<ReportCodecsModule> {}
    public record CrateReport()       implements Exportable._Class<ReportCodecsModule> {}
    public record ModuleResult()      implements Exportable._Class<ReportCodecsModule> {}
    public record FindingReport()     implements Exportable._Class<ReportCodecsModule> {}
    public record RuleSetReport()     implements Exportable._Class<ReportCodecsModule> {}
    public record RuleReport()        implements Exportable._Class<ReportCodecsModule> {}

    public record ConformanceReportCodec() implements Exportable._Class<ReportCodecsModule> {}
    public record CrateReportCodec()       implements Exportable._Class<ReportCodecsModule> {}
    public record ModuleResultCodec()      implements Exportable._Class<ReportCodecsModule> {}
    public record FindingReportCodec()     implements Exportable._Class<ReportCodecsModule> {}
    public record RuleSetReportCodec()     implements Exportable._Class<ReportCodecsModule> {}
    public record RuleReportCodec()        implements Exportable._Class<ReportCodecsModule> {}

    @Override public ImportsFor<ReportCodecsModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<ReportCodecsModule> exports() {
        return new ExportsOf<>(INSTANCE, List.of(
                new ConformanceReport(), new ConformanceReportCodec(),
                new CrateReport(),       new CrateReportCodec(),
                new ModuleResult(),      new ModuleResultCodec(),
                new FindingReport(),     new FindingReportCodec(),
                new RuleSetReport(),     new RuleSetReportCodec(),
                new RuleReport(),        new RuleReportCodec()));
    }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        var lines = new ArrayList<String>();
        lines.add("// Generated by ReportCodecsModule from ReportCodecManifest - do not hand-edit.");
        for (ObjectDefinition<?> def : ReportCodecManifest.ENTRIES) {
            lines.add(EcmaDefinitionCodeGen.INSTANCE.generate(def));
            lines.add(EcmaFunctionsCodeGen.INSTANCE.generate(def));
        }
        return lines;
    }
}
