package hue.captains.singapura.js.homing.catalogue.widgets;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/**
 * The catalogue party's type, as the page has it: {@code CATALOGUE}, generated from
 * {@link CatalogueChoice#TYPE} - so every message is checked against what Java declared.
 */
public record CatalogueChoiceModule() implements EsModule<CatalogueChoiceModule>, SelfContent {

    public static final CatalogueChoiceModule INSTANCE = new CatalogueChoiceModule();

    public record CATALOGUE() implements Exportable._Constant<CatalogueChoiceModule> {}

    @Override public ImportsFor<CatalogueChoiceModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<CatalogueChoiceModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new CATALOGUE())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by CatalogueChoiceModule from CatalogueChoice.TYPE - do not hand-edit.", CatalogueChoice.TYPE.js());
    }
}
