package hue.captains.singapura.js.homing.docview.gallery;

import hue.captains.singapura.js.homing.core.EsModule;
import hue.captains.singapura.js.homing.core.ExportsOf;
import hue.captains.singapura.js.homing.core.Exportable;
import hue.captains.singapura.js.homing.core.ImportsFor;
import hue.captains.singapura.js.homing.core.ModuleNameResolver;
import hue.captains.singapura.js.homing.core.SelfContent;

import java.util.List;

/** The gallery's specimens, as the page has them: {@code GALLERY_SPECIMENS}, generated from {@link Specimens}. */
public record SpecimensModule() implements EsModule<SpecimensModule>, SelfContent {

    public static final SpecimensModule INSTANCE = new SpecimensModule();

    public record GALLERY_SPECIMENS() implements Exportable._Constant<SpecimensModule> {}

    @Override public ImportsFor<SpecimensModule> imports() { return ImportsFor.noImports(); }

    @Override
    public ExportsOf<SpecimensModule> exports() { return new ExportsOf<>(INSTANCE, List.of(new GALLERY_SPECIMENS())); }

    @Override
    public List<String> selfContent(ModuleNameResolver resolver) {
        return List.of("// Generated by SpecimensModule from Specimens - do not hand-edit.", Specimens.js());
    }
}
